spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: sys
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: System
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  
server:
  port: 9090
  servlet:
    context-path: /SSA
  